source :rubygems

gem 'eventmachine', '1.0.0.beta.3'  
gem 'em-http-request', :git => 'git://github.com/igrigorik/em-http-request.git'
gem 'em-synchrony', :git => 'git://github.com/igrigorik/em-synchrony.git'

gem 'ruby-debug19', :platforms => :mri_19
